filter:
    excluded_paths: [include/simple_html_dom.php]

tools:
    js_hint: true

    php_mess_detector: true
    php_analyzer: true
    php_cpd: true
    php_pdepend: true
    php_code_sniffer:
        config:
            standard: "WordPress"